
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcsemdhxtjsxwhuhhqvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjc2VtZGh4dGpzeHdodWhocXZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3Njg0NjAsImV4cCI6MjA1OTM0NDQ2MH0.feG9ViOpbwz-LwKnbyUwMTSEBzvB6PFXTOOgzlu5_OA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
